

export const REGISTER_USER="REGISTER_USER"
export const Reg_SUCCESS="Reg_SUCCESS"
export const Reg_FAILURE="Reg_FAILURE"


export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"
export const LOGIN_USER="LOGIN_USER"






export const GET_DATA_REQUEST="GET_DATA_REQUEST";
export const GET_DATA_ERROR="GET_DATA_ERROR";
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS";



export const ADD_DATA_REQUEST='ADD_DATA_REQUEST';
export const ADD_DATA_SUCCESS='ADD_DATA_SUCCESS';
export const ADD_DATA_FAILURE='GET_DATA_FAILURE';


export const DELETE_DATA_SUCCESS="DELETE_DATA_SUCCESS"
export const DELETE_DATA_FAILURE="DELETE_DATA_FAILURE"

export const UPDATE_DATA_REQUEST='UPDATE_DATA_REQUEST';
export const UPDATE_DATA_SUCCESS='UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_FAILURE='UPDATE_DATA_FAILURE';
